### PR TITLE
New terminate

### PR DESCRIPTION
**Pull request by Dan-Dongcheol-Lee**
Lets merge the branch to master after quick code review.
Feel free to cancel the pull request if we need to do more things on the branch.

### CODE REVIEW

**Comment by LarsOL** [comment]
Considering this has essentially been master since the middle of last year. We really should merge this @tinhtruong @codedance. I think @Dan-Dongcheol-Lee @hiroxy and I already approve.

Anything that is stopping this?

**Comment by hiroxy** [comment]
Have fixed the conflicts

**Review by LarsOL — APPROVED** [review]

**Comment by Dan-Dongcheol-Lee** [comment]
@LarsOL , realised that this pull request contains cache control request headers in pc-updater, which needs to be done with more tests not only unit tests, we can merge it later.

**Comment by Dan-Dongcheol-Lee** [comment]
Sorry guys, realised that this pull request excludes my changes which I had reverted when I was closing this. didn't see the logs of reverted messages. 
Therefore, it would be all right to be merged once approved.

**Comment by hiroxy** [comment]
- `Test_Execute_ShouldExecuteNormalCommandProperly` in the `cmdutil` package and `Test_ProcessKillGracefully_GUIProgram` in the `osutils` package fail because OS specific absolute paths are used
- `Test_ExecuteRandomStartupDelayTask` and `Test_ExecuteTask_GracefulShutDown_OK` in `svcutil` pacakge are flaky test cases

**Comment by hiroxy** [comment]
I've fixed the issues I commented.

**Comment by Dan-Dongcheol-Lee** [comment]
thanks Hiroshi!

**Review by hiroxy — APPROVED** [review]

**Review by tinhtruong — APPROVED** [review]
Looking good!
Let's merge!

**Pull request merged**
